### PR TITLE
Features/lease ups page #154064502

### PR DESCRIPTION
**Pull request by fddayan**
https://www.pivotaltracker.com/story/show/154064502

We need to merge first #38 (centralized mapping) in order to review this PR.

### CODE REVIEW

**Comment by chrisdolendo** [comment]
Review instructions worked as an admin but it looks like when logged in as a leasing agent it breaks at https://dahlia-lap-full-pr-46.herokuapp.com/listings/lease_ups/a0W0P00000DZfSpUAL/applications. It might be because Organization_URL__c is not accessible as a leasing agent. I will contact Rachael/Krissy regarding this but please follow up with them about it.

**Comment by fddayan** [comment]
@chrisdolendo I do not see a `Organization_URL__c` in Listing__c` in the schema builder or the workbench. Perhaps they removed that field?

**Comment by fddayan** [comment]
@chrisdolendo, Kristen pointed out that `Organization_URL__c`, was removed. I removed this field from our query and now it works. You can review again

**Comment by callaghanc** [comment]
@fddayan looks pretty good! i made some updates to the way we've been naming lease up listings and lease up listing applications, i realized we can make the naming more clear to better indicate what objects are being handled when - i.e. whether we are dealing with listings that have lease up status, or with applications belonging to a listing that has lease up status. i also made the lease ups page route use a dash instead of an underscore to match what we've been doing so far with path formatting.

would you be able to update this PR so that the text alignment of the lease up listings table's headers and cells matches the text alignments seen in Jesse's mockup? https://projects.invisionapp.com/share/ACEZNG43Y#/screens/269642678_Lease_Up_MVP

and could you also do the same text alignment update on the lease up listing applications table, so we maintain consistency? mockup here: https://projects.invisionapp.com/share/ACEZNG43Y#/screens/269807125_MVP_1

**Review by callaghanc — CHANGES_REQUESTED** [review]
@fddayan looks pretty good! i made some updates to the way we've been naming lease up listings and lease up listing applications, i realized we can make the naming more clear to better indicate what objects are being handled when - i.e. whether we are dealing with listings that have lease up status, or with applications belonging to a listing that has lease up status. i also made the lease ups page route use a dash instead of an underscore to match what we've been doing so far with path formatting.

would you be able to update this PR so that the text alignment of the lease up listings table's headers and cells matches the text alignments seen in Jesse's mockup? https://projects.invisionapp.com/share/ACEZNG43Y#/screens/269642678_Lease_Up_MVP

and could you also do the same text alignment update on the lease up listing applications table, so we maintain consistency? mockup here: https://projects.invisionapp.com/share/ACEZNG43Y#/screens/269807125_MVP_1

**Comment by fddayan** [comment]
@callaghanc ready, jesse updated the alignment

**Review by callaghanc — APPROVED** [review]
👍 looks great!

**Comment by chrisdolendo** [comment]
@fddayan ready to merge! just fix the conflicts and make sure the conflict fixes don't break master :)

**Pull request merged**
