### PR TITLE
Update ruby version to 2.7.0 #171402266

### PR DESCRIPTION
**Pull request by LoganArnett**
This PR is for ticket [#171402266](https://www.pivotaltracker.com/story/show/171402266) to upgrade the ruby version

### CODE REVIEW

**Comment by akegan** [comment]
@LoganArnett for AC #2 in this ticket can you update other packages with security vulns in this PR too? https://github.com/SFDigitalServices/sf-dahlia-lap/network/alerts <- let me know if you can't access that page

**Comment by akegan** [comment]
Another note is that we'll have to update semaphore settings to the new ruby version to get this PR to pass, once the rest of the updates are in here I can do that.

**Comment by LoganArnett** [comment]
@akegan I get a 404 on that link

**Comment by akegan** [comment]
Looks like review app deploy failed, with the error:  "Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-cssnext'".

I added you to the review app so you should be able to see the whole build log https://dashboard.heroku.com/apps/dahlia-lap-full-pr-342/activity/builds/15a591d4-feb9-4309-9a0d-7e836049804c

**Comment by akegan** [comment]
@LoganArnett I'm having a hard time finding good documentation of exactly which versions are supported on which stacks, but my guess is that we'll have to upgrade to the heroku-18 stack. 

We can do that by specifying the stack in app.json
```
{
   "stack": "heroku-18"
}
```

**Comment by akegan** [comment]
@LoganArnett looks like upgrading the stack didn't work, it might actually be an issue with postcss-cssnext?

It's installing for me locally ok but for some reason not on heroku 🤔 

Looks like that package is also deprecated?
https://moox.io/blog/deprecating-cssnext/

**Comment by akegan** [comment]
uh oh, semaphore doesn't support ruby 2.7 yet, looks like they only support it for semaphore 2.0. I am not sure how to procede. We could:
1. Try to see if we can install ruby 2.7 ourselves on the stack
2. Transfer to semaphore 2.0 (probably not worth it)
3. Have this PR blocked by the transfer to CircleCI.

What do you think @LoganArnett ?

**Comment by akegan** [comment]
I'm going to try installing the right version according to these docs 🤞

**Comment by LoganArnett** [comment]
I think blocking it by the CircleCI ticket would make sense

**Comment by akegan** [comment]
installing ruby 2.7.0 seems to be working, just need to get the right node version working now

**Comment by akegan** [comment]
@LoganArnett setup is working but rake spec is failing now on semaphore. so we might be ok https://semaphoreci.com/exygy/sf-dahlia-lap/branches/chore-upgrade-ruby-version-171402266/builds/9. 

was rake spec working for you locally?

**Comment by akegan** [comment]
I was able to reproduce the rspec test locally, looking into fixing it now 🤞

**Comment by akegan** [comment]
Just pushed a fix for rspec tests that should work and not affect behavior in the app 🤞

**Comment by akegan** [comment]
e2e tests failing now, but at least the other tests passed 🎉. Looking into it now

**Comment by akegan** [comment]
Looks like it's mostly:
```
ConfirmedHouseholdIncome.js:104 Uncaught TypeError: Cannot read property 'name' of undefined
    at ConfirmedHouseholdIncome.js:104
    at Array.map (<anonymous>)
    at ConfirmedHouseholdIncome (ConfirmedHouseholdIncome.js:102)
    at renderWithHooks (react-dom.development.js:14799)
    at updateFunctionComponent (react-dom.development.js:16978)
    at beginWork (react-dom.development.js:18505)
    at HTMLUnknownElement.callCallback (react-dom.development.js:191)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:240)
    at invokeGuardedCallback (react-dom.development.js:293)
    at beginWork$1 (react-dom.development.js:23057)
(anonymous) @ ConfirmedHouseholdIncome.js:104
ConfirmedHouseholdIncome @ ConfirmedHouseholdIncome.js:102
renderWithHooks @ react-dom.development.js:14799
updateFunctionComponent @ react-dom.development.js:16978
beginWork @ react-dom.development.js:18505
callCallback @ react-dom.development.js:191
invokeGuardedCallbackDev @ react-dom.development.js:240
invokeGuardedCallback @ react-dom.development.js:293
beginWork$1 @ react-dom.development.js:23057
performUnitOfWork @ react-dom.development.js:22024
workLoopSync @ react-dom.development.js:21997
performSyncWorkOnRoot @ react-dom.development.js:21615
(anonymous) @ react-dom.development.js:11133
unstable_runWithPriority @ scheduler.development.js:661
runWithPriority$1 @ react-dom.development.js:11079
flushSyncCallbackQueueImpl @ react-dom.development.js:11128
flushSyncCallbackQueue @ react-dom.development.js:11116
scheduleUpdateOnFiber @ react-dom.development.js:21058
dispatchAction @ react-dom.development.js:15636
(anonymous) @ ConfirmedHouseholdIncome.js:53
react-dom.development.js:19413 The above error occurred in the <ConfirmedHouseholdIncome> component:
    in ConfirmedHouseholdIncome (at SupplementalApplicationContainer.js:74)
    in div (at ContentSection.js:36)
    in Unknown (at ContentSection.js:45)
    in Unknown (at SupplementalApplicationContainer.js:73)
    in ContentSection (at SupplementalApplicationContainer.js:69)
    in ConfirmedHousehold (at SupplementalApplicationContainer.js:184)
    in form (at SupplementalApplicationContainer.js:173)
    in ReactFinalForm (at SupplementalApplicationContainer.js:160)
    in SupplementalApplicationContainer (at context.js:16)
    in ContextComponent (at SupplementalApplicationPage.js:348)
    in div (at AppCard.js:5)
    in AppCard (at CardLayout.js:21)
    in section (at TabCard.js:17)
    in TabCard (at TabsSection.js:11)
    in TabsSection (at CardLayout.js:20)
    in CardLayout (at SupplementalApplicationPage.js:347)
    in SupplementalApplicationPage (created by MapProps)
    in MapProps
```

continuing to look into it...

**Comment by akegan** [comment]
I found the confirmed household income issue, another case of referencing a key via a symbol or string notation (:Id vs 'Id') 🤔 

I can't find anything about this change in the changelog for ruby, so I'm confused about where it's coming from and a bit nervous about it affecting other things silently. Going to keep looking into it.

**Comment by akegan** [comment]
I think it's probably the json gem update from 2.2.0 to 2.3.0, but they don't have a changelog for their update 😱. 

Lots of untidy commits in the changelog https://github.com/flori/json/compare/v2.2.0...v2.3.0

**Comment by akegan** [comment]
getting a weird duplicate field update comment thing going on:
image

I did 2 comments, one with a switch to waitlist, one with a switch to appealed. It's duplicating the last comment without a substatus and then adding a new one. Will check on master to see if it's because of these changes. 


Update: it's a bug in prod too, made a separate ticket to track

**Review by akegan — APPROVED** [review]
I think this is good to go. Merging now

**Pull request merged**
