### PR TITLE
Add delete functionality [DAH-93]

### PR DESCRIPTION
**Pull request by james-wills-sf**
Ticket: [DAH-93]

- hook up delete button functionality
- create a new lease even if it's empty but you're in edit mode

[DAH-93]: https://sfgovdt.jira.com/browse/DAH-93

### CODE REVIEW

**Comment by akegan** [comment]
@james-wills-sf I think review instructions are going to be a bit ridiculous on this ticket, but can you make sure that you add that we need to test all this behavior logged in as a leasing agent too? Especially lease delete because msol had to add the permission

**Comment by akegan** [comment]
somehow got into a state where if I click edit lease on https://dahlia-lap-full-pr-404.herokuapp.com/applications/a0o0P00000IvWgcQAF/supplementals then The new rental assistance panel is opening up. 
Screen Shot 2020-09-15 at 10 12 44 AM

I'll leave this app in that state so you can check it out

Another note with this: If you have the new rental assistance panel and an edit panel open and you click cancel on the edit panel it closes the new panel too 🤔

**Comment by james-wills-sf** [comment]
@akegan Okay I made some non-trivial changes to how the rental assistance code works:

- View state that only pertains to the RentalAssistance component now lives in that component.
  - This means the SupplementalApplicationPage component no longer sets showNewRentalAssistanceButton, etc
- Only the top-level RentalAssistance component is connected to the store, other components get everything through props
  - This makes reasoning about rental assistance state logic much simpler, it's all in the cluster of handler functions in the RentalAssistance render
- I deleted the Panel component
  - once I removed the store connection this component wasn't doing much
- I made sure we're clearing out rental assistances in the react state on delete
  - this was a bug that wasn't handled before.
- I made sure "cancel" deleted the modified rental assistances
  - this was a bug that wasn't handled before

Another possible behavior change: we're not restricting which panels you can have open at once. If you open an edit panel and then the "Add new assistance" panel, that's fine we keep both open.

## Screencast: panel open/close behavior
opening and closing assistances

## Screencast: cancel closes all panels and keeps them closed
cancel closes panels

**Review by akegan — APPROVED** [review]
Not sure I did all the same QA steps again but everything seems to be working as expected and the bug I found before is not showing up again so should be good

**Pull request merged**
