### PR TITLE
Update master with production after Hotfix 10-22-18 release

### PR DESCRIPTION
**Pull request by callaghanc**
@akegan Here's the PR for merging production into master after the hotfix release we did yesterday.

### CODE REVIEW

**Comment by akegan** [comment]
@callaghanc is this ready to be merged? do you want to resolve the conflicts or do you want me to?

**Review by akegan — APPROVED** [review]

**Comment by akegan** [comment]
and remember to merge, not squash and merge!

**Comment by callaghanc** [comment]
You can go ahead and do that if you have time now, or I can do it after I wrap up some Salesforce things.

**Comment by akegan** [comment]
ok I'll fix merge conflicts now

**Pull request merged**
