### PR TITLE
Chores/refactor controller #157578818

### PR DESCRIPTION
**Pull request by fddayan**

### CODE REVIEW

**Comment by fddayan** [comment]
@chrisdolendo @creativecoder @callaghanc 

I think all should take a look at this PR. I made fundamental changes about how the app is structued and I took the liberty (don't hate me 😄) to rename some routes.
I do not know if Chris told you, but I have "clean code obsessive compulsive disorder"  😅  .
I'm happy to rollback any changes if it does not work out.

You an go to the controllers folder and `routes.rb` to take a look

These are the routes that you care about:

# Before

```
     listing_applications GET      /listings/:listing_id/applications(.:format)            applications#listing_index
  new_listing_application GET      /listings/:listing_id/applications/new(.:format)        applications#new
        listing_lease_ups GET      /listings/:listing_id/lease_ups(.:format)               lease_ups#index
                 listings GET      /listings(.:format)                                     listings#index
                  listing GET      /listings/:id(.:format)                                 listings#show
 spreadsheet_applications GET      /applications/spreadsheet(.:format)                     applications#spreadsheet
             applications GET      /applications(.:format)                                 applications#index
         edit_application GET      /applications/:id/edit(.:format)                        applications#edit
              application GET      /applications/:id(.:format)                             applications#show
     flagged_applications GET      /flagged_record_sets/:id/flagged_applications(.:format) flagged_record_sets#flagged_applications
     pending_review_index GET      /flagged_record_sets/pending_review_index(.:format)     flagged_record_sets#pending_review_index
   marked_duplicate_index GET      /flagged_record_sets/marked_duplicate_index(.:format)   flagged_record_sets#marked_duplicate_index
```

# After

```
     listing_applications GET      /listings/:listing_id/applications(.:format)     listings/applications#index
  new_listing_application GET      /listings/:listing_id/applications/new(.:format) listings/applications#new
        listing_lease_ups GET      /listings/:listing_id/lease_ups(.:format)        listings/lease_ups#index
                 listings GET      /listings(.:format)                              listings#index
                  listing GET      /listings/:id(.:format)                          listings#show
 spreadsheet_applications GET      /applications/spreadsheet(.:format)              applications#spreadsheet
            flagged_index GET      /applications/flagged(.:format)                  applications/flagged#index  (Supports a "type" parameter for pending and duplicated view)
                  flagged GET      /applications/flagged/:id(.:format)              applications/flagged#show
             applications GET      /applications(.:format)                          applications#index
         edit_application GET      /applications/:id/edit(.:format)                 applications#edit
              application GET      /applications/:id(.:format)                      applications#show
```

**Comment by callaghanc** [comment]
@fddayan In general this seems good, I like that the flagged app-related routes are shortened up. Where do you see the Lease Ups page fitting into this? But maybe that's beyond the scope of this chore and should be left for the actual story for doing the Lease Ups page.

**Comment by fddayan** [comment]
@chrisdolendo @callaghanc ready for review again:

This route added:

```
lease_up_applications GET      /listings/lease_ups/:lease_up_id/applications(.:format) listings/lease_ups/applications#index
```

**Comment by callaghanc** [comment]
@fddayan Thanks for making those updates! It looks like we still need to account for the Lease Ups page - the page that shows all listings that have the status of "Lease Up" - as we discussed this morning. However, we have a whole feature story coming up dedicated to creating that Lease Ups page, and it would be good to get this chore wrapped sooner than later, especially since the page header open PR is somewhat waiting on this. So I am ok with accepting the good progress this PR represents and letting the Lease Ups page + routes be dealt with in the upcoming dedicated story.

@chrisdolendo Let us know if you agree with the above or if you have a different idea.

**Review by callaghanc — APPROVED** [review]
approved on my side, would like @chrisdolendo's ok before merging

**Comment by creativecoder** [comment]
These changes seem good to me. Are the tests passing? If so, I don't see any reason to have them commented out. I'd only comment out the tests that aren't yet working.

**Comment by fddayan** [comment]
@creativecoder we are going to take care of the tests in a different chore. Tests are not stable, that's why I commented them out. I left them as a reference for the person working on implementing the test (probably me anyway :) but in later time)

**Comment by chrisdolendo** [comment]
Great refactor and collab. I checked the routes and did some QA and it looks good. Let's merge asap to mitigate conflicts :)

**Pull request merged**
