### PR TITLE
Removed loader and added saving text #164967254

### PR DESCRIPTION
**Pull request by LoganArnett**
This PR addresses Pivotal [#164967254](https://www.pivotaltracker.com/story/show/164967254)

I also added in a `start` script that allows us to run the project with only 1 terminal window and one command for both services using `npm-run-all`. I also added a note to the README in relation to this script as well as a little help hint that I didn't realize I needed when installing

### CODE REVIEW

**Comment by akegan** [comment]
@LoganArnett heads up looks like unit tests are failing. You may just need to update snapshots with `yarn run unit -u`

**Review by akegan — CHANGES_REQUESTED** [review]
Did a quick QA locally, all looks good. Just one more AC to meet:

2. Disable status modal buttons when saving as well.

Now that we don't have the full page loading state, we want to make sure that users aren't clicking around and trying to save multiple ways while the page is loading.

Here are the buttons to disable:

Button where it says "Processing" here at the bottom of the page:
image

and these two buttons at the top of the page too ("Processing" and "Add a comment":
image

**Comment by LoganArnett** [comment]
Updated this with the disabled state for the dropdowns and the add comment button

**Comment by akegan** [comment]
@LoganArnett looks like you need to update snapshots again after this change

**Comment by akegan** [comment]
also just found one more button to disable, whoops. It's in the status history at the bottom of the page. 
image

So many buttons to save on one page!

**Comment by LoganArnett** [comment]
True, didnt think about that, sending the updated snapshots now

**Comment by LoganArnett** [comment]
Checking on the e2e issue now

**Comment by LoganArnett** [comment]
Looks like the flaky tests like you mentioned, all passing now

**Review by akegan — APPROVED** [review]

**Comment by akegan** [comment]
Looks good, just needs snapshots updated again

**Pull request merged**
