### PR TITLE
Merge Caritas Updates

### PR DESCRIPTION
**Pull request by akegan**
Here's a branch off of pre-prod we can update to resolve merge conflicts. 

Here's a list of all of the features to QA. 

- [x] Update Date Input in LAP
- [x] Add language submitted in field to paper short form
- [x] Add address fields for Alternate Contact to LAP paper applications
- [x] Required fields on paper applications should have inline validation
- [x] Required fields on Preferences on paper applications should have inline validation
- [x] Provide leasing agent with a preview of saved application and button to create new application
- [x] Alt Contact Address should show in View State of Short Form

### CODE REVIEW

**Comment by chrisdolendo** [comment]
@akegan @callaghanc @jrubenoff @slowbot 

Merge conflicts are fixed with @fddayan! 🎉 Smoke testing please! 💃

**Comment by akegan** [comment]
Add preferences button is disabled until a household member is added now, it should just be if last/first name and dob are not filled in

**Comment by akegan** [comment]
Preference validation seems to not be wired up.

**Comment by akegan** [comment]
this warning showing up in the console could have something to do with it:
image

**Comment by akegan** [comment]
Looks like live/work preference still has a bug when you select it:

image


I'm also only seeing the primary applicant as a household member in the dropdown for all of the preferences, is that expected behavior?

**Comment by akegan** [comment]
Remaining bugs:

- [x] Application language doesn't appear to be working correctly, it's not saving right
- [x] COP and DTHP certificate fields are not saving and loading on application edit. 
- [x] Alternate contact mailing fields are not saving
- [x] Household members other than primary applicant are not showing up in applicant member dropdown

**Comment by akegan** [comment]
@chrisdolendo @fddayan @callaghanc I believe all of the bugs are fixed and the features are tested! Additional QA would be much appreciated though!

**Comment by callaghanc** [comment]
@akegan Did a bit of QA, looks like on the application form the household member DOB field is required by Salesforce but not required by the form, so it's possible to submit the form with an incomplete (DOB-less) household member and then you get a submit error, with no indication that the HH member DOB is required. We have the HH member DOB field required on master - do you know if there have already been decisions made around the goal for this field's validations? Otherwise looks like this may have just gotten lost in the shuffle.

**Comment by akegan** [comment]
@callaghanc I don't believe requiring a dob for a household member if other fields are present was part of the original feature set

**Comment by callaghanc** [comment]
After further discussion with @akegan we clarified that requiring DOB for HH member is a current feature on master that is being broken by this merge; it was not a requirement in the Caritas work. We will go ahead with the merge and create a bug story to fix this issue post-merge.

**Pull request merged**
