### PR TITLE
Partners Release Week of 05/05/20

### PR DESCRIPTION
**Pull request by james-wills-sf**

### CODE REVIEW

**Comment by james-wills-sf** [comment]
@akegan testing mention notification

**Comment by james-wills-sf** [comment]
@akegan testing again

**Comment by james-wills-sf** [comment]
@james-wills-sf testing self mentions

**Comment by james-wills-sf** [comment]
@james-wills-sf testing self mentions again

**Comment by akegan** [comment]
@james test slack notifications

**Pull request merged**
