### PR TITLE
Chores/update activejob gem #162466430

### PR DESCRIPTION
**Pull request by akegan**
https://www.pivotaltracker.com/story/show/162466430

### CODE REVIEW

**Comment by akegan** [comment]
Note, for this one I got this message when doing the rails update. 

> HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
> But that may break your application.
> 
> Please check your Rails app for 'config.i18n.fallbacks = true'.
> If you're using I18n 1.1.x and Rails (< 6.0), this should be
> 'config.i18n.fallbacks = [I18n.default_locale]'.
> If not, fallbacks will be broken in your app by I18n 1.1.x.
> 
> For more info see:
> https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

**Comment by chrisdolendo** [comment]
We're using gem 'rails', '~> 5.1.x' not 6+ so we may be fine with what you found. How come the update is just on the gemfile.lock? We're not indicating a version on gemfile? It's fine either way.

**Comment by akegan** [comment]
@chrisdolendo just updated to include the rails update in the gemfile too

**Comment by chrisdolendo** [comment]
@akegan I don't see the change -- can you point me to the commit?

**Comment by akegan** [comment]
@chrisdolendo my bad. github had rejected my push because I hadn't pulled in latest master 🙁. Pushed now! https://github.com/Exygy/sf-dahlia-lap/pull/178/commits/e61d8ae0bdf24140277e808d1c39f180e524a274

**Review by chrisdolendo — APPROVED** [review]
:+1:

**Pull request merged**
