### PR TITLE
Features/change pref zipcode to zip #161761767

### PR DESCRIPTION
**Pull request by callaghanc**

### CODE REVIEW

**Comment by akegan** [comment]
@callaghanc I tried changing the base on this to prod rather than master and it didn't work very well. It looks like this might be something where we have to create a followup ticket to track the changes that will need to be made in the domain files that have been updated on master since the last release. 

That might even look like having 2 prs associated with this ticket and keeping this one and opening up a separate one off of production (or the new nov-timed-release branch that I just created)

**Comment by akegan** [comment]
@callaghanc I just changed the base of this PR back to master since it's going to go out after our lap release.

**Comment by akegan** [comment]
is there any other work that needs to get done on this one?

**Comment by callaghanc** [comment]
@akegan Nope, just needed a decision on PR base and needs tests to pass

**Review by akegan — APPROVED** [review]
Looks good to me

**Comment by akegan** [comment]
this PR looks good to me, but the story needs review instructions

**Comment by akegan** [comment]
@callaghanc not sure if you saw this, but this ticket needs review instructions then you're good to go to deliver!

**Comment by callaghanc** [comment]
@akegan review instructions added and story delivered

**Pull request merged**
