### PR TITLE
Chores/Update release script to use JIRA ticket links

### PR DESCRIPTION
**Pull request by james-wills-sf**
Example spreadsheet output: https://docs.google.com/spreadsheets/d/1EUvw2ugaFprt8FxlCUa1yWATSn0KKo4FyRfBJWUwE3M/edit#gid=946901404

Example draft release output (after shifting some things around + adding a screenshot): https://github.com/SFDigitalServices/sf-dahlia-lap/releases/tag/untagged-218248c3039c780e2540

- 2020-09-01 at 3 31 21 PM

### CODE REVIEW

**Review by akegan — APPROVED** [review]
Looks reasonable. I still haven't used it yet but hope to someday!

**Comment by akegan** [comment]
how is it getting the multiple PRs associated with a ticket?

**Comment by james-wills-sf** [comment]
@akegan it's not, I did that manually

**Comment by akegan** [comment]
ah OK cool. So it'll default to showing every commit. Just wanted to make sure we wouldn't drop anything 😄

**Pull request merged**
