### PR TITLE
Remove email and phone and add substatus to apps table DAH-580

### PR DESCRIPTION
**Pull request by akegan**
DAH-580

I found a bug where substatus and status_last_updated date weren't changing when you changed the status. I fixed that but wasn't able to get a test working.

The last commit pushed just has a bunch of logs and a test I was trying to write, which could be a good starting point or could be a commit to just get rid of.

### CODE REVIEW

**Review by james-wills-sf — APPROVED** [review]
QA'd with admin and leasing agent

**Comment by akegan** [comment]
@james-wills-sf did you end up being able to get the tests I tests I started working?

**Comment by james-wills-sf** [comment]
@akegan so all I had to do was delete a vcr and re-run. I didn't see a commit with a half finished test pushed so I assumed you reverted it?

**Comment by akegan** [comment]
oh darn, I guess it didn't push, oh well. I'll put up a new PR with the tests I wanted to add once I get them working

**Pull request merged**
