### PR TITLE
Use status updated date from application instead of doing separate query DAH-591

### PR DESCRIPTION
**Pull request by akegan**
DAH-591

The code is done for this, but there is data missing from before the field was added (around 10/8). We probably shouldn't merge + deploy until we get that sorted so there isn't missing data on prod

[working with larry on slack](https://sfinnovation.slack.com/archives/CPZHGET3R/p1605050178007500) to figure out how to resolve the data issue.

### CODE REVIEW

**Review by james-wills-sf — APPROVED** [review]
@akegan code lgtm. Tried it out and the request feels a little faster but you're right, I'm seeing last updated = "none" for every row. Probably should QA again after the data is backfilled

**Comment by akegan** [comment]
update on this: Larry is working on the data fixes. We're going to test in full before going to prod

**Comment by akegan** [comment]
@james-wills-sf this is ready for QA again now that Larry has updated the data. He only updated 1400 MISSION UNIT 1100 so you'll have to QA with that listing

**Review by james-wills-sf — APPROVED** [review]
@akegan looks good!

**Pull request merged**
