### PR TITLE
Update query for applications #171886409

### PR DESCRIPTION
**Pull request by LoganArnett**
This PR is for [ticket #171886409](https://www.pivotaltracker.com/story/show/171886409)

### CODE REVIEW

**Comment by akegan** [comment]
changes look good on this, just need to do QA

**Review by akegan — APPROVED** [review]
changes look good. Testing is a bit wonky on full because the refresh updated the created date for all applications to today. I deployed to pre-prod to test.

Tests are failing but they are still failing on master post-refresh so I wouldn't put time into trying to fix them yet.

**Comment by akegan** [comment]
@LoganArnett I've pulled in latest master that should have passing tests, but looks like there's still at least one backend tests if you're up for fixing.

**Comment by LoganArnett** [comment]
Ok I will check it out

**Comment by akegan** [comment]
@LoganArnett does this branch have your latest changes on it?

**Pull request merged**
