### PR TITLE
Remove auto calculated ami #171507842

### PR DESCRIPTION
**Pull request by LoganArnett**
This PR is for ticket [#171507842](https://www.pivotaltracker.com/story/show/171507842)

### CODE REVIEW

**Comment by akegan** [comment]
@LoganArnett FYI  rspec tests are failing

**Comment by LoganArnett** [comment]
@akegan updated for RSpec issues

**Comment by akegan** [comment]
getting weird behavior or 450 folsom listing 
image

looks like it should be TCAC and HUD adjusted:
image

if at all possible we'd like to unite the two dropdowns in some way too in case there are conflicts or not show the year dropdown but send the year info to the API? Maybe it would be easiest to make it one dropdown and have the value be e.g. "HUD Adjusted - 2018"?

**Comment by akegan** [comment]
I should hopefully have time tomorrow afternoon to hop on a call if that would help clarify!

**Comment by LoganArnett** [comment]
Updated UI:
s

**Review by akegan — APPROVED** [review]
Looks good! good to merge

**Pull request merged**
