### PR TITLE
fix: DAH-3031 limit fields selected in soql query for rental fcfs

### PR DESCRIPTION
**Pull request by alulabeshue-sfgov**
## Description

Limit the fields that are selected in a rental fcfs SOQL query to the fields that are actually needed by the frontend

## Jira ticket

https://sfgovdt.jira.com/browse/DAH-3031

### Version Control

- [x] branch name begins with `angular` if it contains updates to Angular code
- [x] branch name contains the Jira ticket number
- [x] PR name follows `type: TICKET-NUMBER Description` format, e.g. `feat: DAH-123 New Feature`

### Code quality

- [x] [the set of changes is small](https://google.github.io/eng-practices/review/developer/small-cls.html#what-is-small)
- [x] all automated code checks pass (linting, tests, coverage, etc.)
- [x] code irrelevant to the ticket is not modified e.g. changing indentation due to automated formatting
- [x] if the code changes the UI, it matches the UI design exactly
- [x] if the changes include human translations, follow the [human translations process](https://sfgovdt.jira.com/l/cp/XS1KpvE4)

### Review instructions

- [x] instructions specify which environment(s) it applies to
- [x] instructions work for PA testers
- [x] instructions have already been performed at least once

### Request review

- [x] PR has `needs review` label
- [x] Use `Housing Eng` group to automatically assign reviewers, and/or assign specific engineers
- [x] If time sensitive, notify engineers in Slack

### CODE REVIEW

**Review by tallulahkay — APPROVED** [review]
This is great! I like how you pared it down to what we actually need

**Review by tallulahkay — COMMENTED** [review]
non-blocking: I'm noticing that the apps stop on page 52 even though there are 55 pages - is this correct?

edit: I think the unranked apps are hidden now for some reason - they should show at the end

**Comment by alulabeshue-sfgov** [comment]
@tallulahkay 

> non-blocking: I'm noticing that the apps stop on page 52 even though there are 55 pages - is this correct?

I noticed this as well, it exists in current prod version as well. I was going to create a separate ticket to look into the paging and keep this to just get past the 1K limit.

> edit: I think the unranked apps are hidden now for some reason - they should show at the end

I believe all of the applications are ranked, Im not seeing an example in full or prod of an unranked application to test against.

**Review by tallulahkay — APPROVED** [review]

**Comment by tallulahkay** [comment]
> @tallulahkay
> 
> > non-blocking: I'm noticing that the apps stop on page 52 even though there are 55 pages - is this correct?
> 
> I noticed this as well, it exists in current prod version as well. I was going to create a separate ticket to look into the paging and keep this to just get past the 1K limit.
> 
> > edit: I think the unranked apps are hidden now for some reason - they should show at the end
> 
> I believe all of the applications are ranked, Im not seeing an example in full or prod of an unranked application to test against.

Cool, I agree about the page size issue - it's suppressing applications without an applicant but not updating the page size. We can create another ticket to fix!

**Pull request merged**
