### PR TITLE
Fix supp app handling of blank currency values and make Total Monthly Rent a currency field #166858654

### PR DESCRIPTION
**Pull request by software-project**
https://www.pivotaltracker.com/story/show/166858654

### CODE REVIEW

**Review by chrisdolendo — APPROVED** [review]
Looks good!

**Comment by callaghanc** [comment]
would like to connect with @software-project briefly about some field transforms before we merge this PR

**Review by callaghanc — DISMISSED** [review]
would like to connect with @software-project briefly about some field transforms before we merge this PR

**Comment by akegan** [comment]
@callaghanc are you up for adding a couple of tests to this PR or updating tests we already have to check for these updates?

**Comment by callaghanc** [comment]
@akegan sure, i can add/update a couple tests, marking this pr wip again until those are added

**Review by akegan — APPROVED** [review]
Looks good. Glad we caught the null vs empty string issue, and thanks for adding tests @callaghanc

**Pull request merged**
