### PR TITLE
Fix filters clearing on pagination [DAH-598]

### PR DESCRIPTION
**Pull request by james-wills-sf**
DAH-598
I was going to add unit tests for this, but they'd be a lot of effort so I skipped them. I can add tests if the reviewer feels strongly about it!

### CODE REVIEW

**Review by akegan — APPROVED** [review]
Bug looks fixed but also looks like we have an issue with combining filters, not likely due to this PR though. Hopefully it's fixed in Marçin's PR. will check there too. 
image

**Comment by james-wills-sf** [comment]
@akegan I'll keep an eye out for that when reviewing marcin's pr.

**Comment by akegan** [comment]
Already confirmed that it's working fine on Marçin's PR, just need to make sure it's included in review instrux too

**Comment by james-wills-sf** [comment]
Added a note to the review instructions for marcin's ticket

**Pull request merged**
