### PR TITLE
Features/status modal error handling #159012470

### PR DESCRIPTION
**Pull request by akegan**
https://www.pivotaltracker.com/story/show/159012470

This is based off of work on the status update saving PR

### CODE REVIEW

**Comment by akegan** [comment]
It looks like the error sampling might be causing e2e tests to fail on this PR. I'll make sure that we get a passing build before merge

**Review by fddayan — APPROVED** [review]
looks good 👍

**Comment by akegan** [comment]
FYI @fddayan I added another line of code to fix a bug if you want to check it out

**Comment by fddayan** [comment]
@akegan looks good 👍

**Pull request merged**
