### PR TITLE
feat: use receives pref for veteran preferences

### PR DESCRIPTION
**Pull request by alulabeshue-sfgov**
[DAH-2336](https://sfgovdt.jira.com/browse/DAH-2336)

[DAH-2336]: https://sfgovdt.jira.com/browse/DAH-2336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tallulahkay** [comment]
@alulabeshue-sfgov The pr app's lease up listings tab doesn't work for some reason - maybe the pr app needs to be rebuilt?

I tested locally and it didn't work as described - left a comment on the ticket

I think you need to update this other place where post_lottery_validation is coming in to make sure it shows up as confirmed: 
- https://github.com/SFDigitalServices/sf-dahlia-lap/blob/main/app/javascript/utils/layeredPreferenceUtil.js#L64
- https://github.com/SFDigitalServices/sf-dahlia-lap/blob/main/app/javascript/components/supplemental_application/sections/PreferencesTable.js#L39

Same issue here on the lease up listing page, where it isn't showing confirmed:
https://github.com/SFDigitalServices/sf-dahlia-lap/blob/ee79b51921f6043da252402df826a266683ed0da/app/javascript/components/lease_ups/LeaseUpApplicationsTable.js#L106

**Comment by alulabeshue-sfgov** [comment]
> The pr app's lease up listings tab doesn't work for some reason - maybe the pr app needs to be rebuilt?

@tallulahkay thanks for catching this, some unleash env variables were missing after merging. I've added them and I am able to load lease up listings now. Can you try again?

> I tested locally and it didn't work as described - left a comment on the ticket
>
> I think you need to update this other place where post_lottery_validation is coming in to make sure it shows up as confirmed:

I've updated the review instructions on the jira ticket. Were you running into the cases where the vet preference receives the preference but the base preference has not yet been confirmed?

**Comment by tallulahkay** [comment]
> I've updated the review instructions on the jira ticket. Were you running into the cases where the vet preference receives the preference but the base preference has not yet been confirmed?

Thank you!! I think I misunderstood the requirements because I didn't know how the base preference was considered. I am seeing the behavior described in the review instructions!

**Review by tallulahkay — APPROVED** [review]
Nice!

**Pull request merged**
