### PR TITLE
Bugs/lease no preference used #164619509

### PR DESCRIPTION
**Pull request by akegan**
Small release bug
https://www.pivotaltracker.com/story/show/164619509

### CODE REVIEW

**Comment by callaghanc** [comment]
@akegan can you see if you can get tests to pass on this? i re-ran them a couple times but they keep failing

**Comment by akegan** [comment]
just tested locally and tests passed once and failed once 🙁. @callaghanc tests just passed on this one, but I think we really need to work on having better indication of why tests are failing and deal with flakiness.

Locally I had problem that I did catch that was an auth error, I wonder if we could instead re-use the authentication somehow

**Comment by callaghanc** [comment]
@akegan agree that we need to spend a little time on addressing the state of these tests to save us time re-running tests going forward, and also to ensure that there isn't some actual intermittent issue that's being ignored.  let's create a chore for improving Partners e2e tests if we don't already have one. we can merge this PR for now

**Review by callaghanc — APPROVED** [review]

**Comment by akegan** [comment]
Ticket made: https://www.pivotaltracker.com/story/show/164644696

**Pull request merged**
