### PR TITLE
[#162591164] Add missing fields to application view

### PR DESCRIPTION
**Pull request by software-project**
https://www.pivotaltracker.com/story/show/162591164

### CODE REVIEW

**Comment by akegan** [comment]
@software-project snapshot tests are failing

**Comment by akegan** [comment]
@software-project can you reorder fields to match the arrangement in [this comment](https://www.pivotaltracker.com/story/show/162591164/comments/200650834)

**Review by akegan — CHANGES_REQUESTED** [review]
see comments above

**Comment by akegan** [comment]
@software-project let's deal with the phone number ordering in your next PR to add the second phone number. 

I think our best bet is probably just to rearrange fields a bit to make it work (e.g. move email above phone number 🤷‍♀️) and we should figure it out once we add those fields we know we're adding

**Review by akegan — APPROVED** [review]

**Comment by software-project** [comment]
@akegan ok, agreed

**Pull request merged**
