### PR TITLE
Update sub status options and tests #165920113

### PR DESCRIPTION
**Pull request by LoganArnett**
This PR covers [ticket #165920113](https://www.pivotaltracker.com/story/show/165920113)

Updated the sub status values and tested validation, there are still errors being thrown by Salesforce so I will put together a list of which ones are still erroring. I checked them against the list on Salesforce and they appear to be correct.

### CODE REVIEW

**Comment by LoganArnett** [comment]
The below values are the ones throwing a 503 error with this message:
"Faraday::ClientError, CANNOT_EXECUTE_FLOW_TRIGGER: We can't save this record because the “Update Application Processing Status” process failed. Give your Salesforce admin these details. This error occurred when the flow tried to update records: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST: Sub Status: bad value for restricted picklist field: {SUB STATUS VALUE HERE}. You can look up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1871162131-175139 (-1818681241)"

## Failing Sub Status Values

### Appealed
  * Appeal meeting scheduled

### Waitlisted
  * Written confirmation sent

### Disqualified
  * Missed 2 or more appointments
  * Under occupancy
  * Over occupancy
  * Under income, no rent subsidy
  * Over income
  * Does not meet criminal background
  * Does not meet other building restrictions
  * Unit did not pass subsidy inspection

### Approved
  * Approval letter sent

**Comment by akegan** [comment]
@LoganArnett larry has fixed substatuses, so it should be working now! please re-test when you're back online tomorrow

**Comment by LoganArnett** [comment]
Tested all of the substatuses and they are now successful, just trying to get the build running on Semaphore

**Comment by akegan** [comment]
@LoganArnett minor QA issue. 

If you select a substatus for one of the statuses with substatus, don't save, then switch to a status without substatus (e.g. "Lease Signed") and try to save, you get this error:
``` << API Error >> Faraday::ClientError, INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST: bad value for restricted picklist field: Waiting for subsidy inspection ```

Looks like you just need to add a line to clear substatus on status change?

**Review by akegan — APPROVED** [review]
Looks good!

**Comment by akegan** [comment]
@LoganArnett don't forget to update PR title on this

**Pull request merged**
