### PR TITLE
Hotfix/fix electronic app submission [DAH-540]

### PR DESCRIPTION
**Pull request by james-wills-sf**
[DAH-540]
### The bug
Editing a supplemental application switched the type to paper and updated the submitted date

### Behavior after fix
Editing a supplemental application doesn't change type or submitted date. Editing a paper application **does** change the submitted date

### Screenshot of fix: before clicking save on supplemental application page
- 2020-09-30 at 12 16 58 PM

### Screenshot of fix: after clicking save on supplemental application page
note that type and creation date didn't change
- 2020-09-30 at 12 23 31 PM

 

[DAH-540]: https://sfgovdt.jira.com/browse/DAH-540

### CODE REVIEW

**Comment by akegan** [comment]
@james-wills-sf can you make a JIRA ticket to track too?

**Comment by james-wills-sf** [comment]
@akegan ticket here: DAH-540

**Comment by akegan** [comment]
@james-wills-sf QAing now, can you add review instructions to the ticket too?

**Comment by akegan** [comment]
@james-wills-sf looks like application submitted date doesn't update when you edit a paper application after all. Just updated this one: https://sfhousing--full.lightning.force.com/lightning/r/Application__c/a0o1F000002NiccQAC/view

**Review by akegan — APPROVED** [review]
Application submission date didn't update for me when I updated a paper application but I don't think that that's a dealbreaker. 

Tested submitting a new paper app and that set the application type and application submitted date as expected. 

Tested the supp app and confirmed that now the application submitted type and the application submitted date are not updating on other application saves.

**Comment by james-wills-sf** [comment]
@akegan I just tried on full and the application submitted date doesn't change there either when editing an old paper app

**Comment by akegan** [comment]
@james-wills-sf OK totally fine then!

**Pull request merged**
