### PR TITLE
Features/validate primary applicant dob #157818358

### PR DESCRIPTION
**Pull request by fddayan**
https://www.pivotaltracker.com/story/show/157818358

We need to merge first https://github.com/Exygy/sf-dahlia-lap/pull/38 (centralized mapping) in order to review this PR.

### CODE REVIEW

**Comment by fddayan** [comment]
@callaghanc merged conflicts fixed

**Review by chrisdolendo — CHANGES_REQUESTED** [review]
@fddayan This url is getting the same error when querying a listing as https://github.com/Exygy/sf-dahlia-lap/pull/43. 

Using this link in the review instructions:
https://dahlia-lap-full-pr-44.herokuapp.com/listings/a0W0x000000GhJUEA0/applications/new

**Comment by fddayan** [comment]
@chrisdolendo fixed and ready for review

**Review by chrisdolendo — APPROVED** [review]
Tested and looks good!

**Comment by chrisdolendo** [comment]
@fddayan thanks for QA testing this! It looks great!

**Comment by chrisdolendo** [comment]
@fddayan story is accepted and the application edit chore is in master, let's resolve these conflicts, do a smoke test and then merge to master :)

**Pull request merged**
