### PR TITLE
Fix grunt command and update stylesheets

### PR DESCRIPTION
**Pull request by james-wills-sf**
The `grunt` command wasn't working because it was trying to use `grunt-replace` instead of `grunt-replace-regex` which is the correct package.

### CODE REVIEW

**Comment by akegan** [comment]
looks good. Do you want to incorporate your stylesheet updates into this PR too?

**Comment by akegan** [comment]
once you merge in the stylesheet changes let's do a quick smoke test to make sure things still look OK since we haven't pulled in latest pattern lib in a while

**Comment by james-wills-sf** [comment]
@akegan smoke testing the app now. Review app is ready if you also want to test

**Comment by james-wills-sf** [comment]
@akegan style fixes are in, this should be ready for re-review along with the associated pattern library pr: https://github.com/SFDigitalServices/sf-dahlia-pattern-library/pull/136

**Comment by akegan** [comment]
Minor issue with spacing on the status modal:
before:
image
after:
image


Still has the checkbox issue where the check is missing too. Might be the way it was imported though? Sometimes icons don't get transferred over correctly. The -14k lines makes me think that that might be the case. i think you may have to run npm start instead of npm build for this repo

**Comment by james-wills-sf** [comment]
@akegan okay, I fixed the status modal margin issue:
- 2020-08-24 at 2 07 16 PM

This fix also included some pattern changes: https://github.com/SFDigitalServices/sf-dahlia-pattern-library/pull/137


And fixed the missing icons:
- 2020-08-24 at 2 08 22 PM

**Comment by james-wills-sf** [comment]
just noticed the status buttons in the lease up applications table have too little top margin, investigating

Update: fixed.

**Review by akegan — APPROVED** [review]
Looks good. thanks for making these fixes. 

Noticed that the status modal dropdowns can't be navigated at all using the keyboard. Overall the app has a lot of accessibility issues, but we should probably still make a ticket to fix it.

**Comment by james-wills-sf** [comment]
@akegan ticket made: [DAHLIAFE-124](https://sfgovdt.jira.com/browse/DAHLIAFE-124?atlOrigin=eyJpIjoiNzcyZWFkOTg2MzI0NDkxZDgzNzMwODAwYTQxY2ViMzYiLCJwIjoiaiJ9)

**Pull request merged**
